#项目访问端口
server:
  port: 20500
  servlet:
    context-path: /

#Spring整合mysql驱动
spring:
  #------------------数据库配置------------------------------
  schema: dev_dusto_dmp
  # 默认所有微服务是用当前数据库链接，如果某一个微服是用单独的数据库，则在内部单独指定即可
  datasource:
    name: main
    # dev 开发环境数据源
    url: jdbc:mysql://172.16.12.116:4000/dev_dusto_dmp?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: retail_uat
    password: Retail.dusto.com
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

#------------------mybatis的配置------------------------------
mybatis:
  # 类别名映射包路径
  type-aliases-package: com.intelligent
  # 全局配置
  configuration:
    # 使用驼峰命名法转换字段
    map-underscore-to-camel-case: true
    # 使全局的映射器启用或禁用缓存
    cache-enabled: false
    # # 控制台打印sql，包含数据
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 自定义转换器包路径
  type-handlers-package: com.intelligent
  #mapper文件扫包配置
  mapper-locations:
    #加载mapper文件
    - classpath:/mapper/**/*.xml
logging:
  level:
    root: info
    com.example: debug
  file:
    path:log/intelligent-app.log





